#!/usr/bin/env bun
/**
 * Fails CI when docs/security/security-memory.md changes without a paired update
 * to the RLS invariants fixture, findings.accepted.json, or a new migration.
 * Symmetric: findings.accepted.json changes require a memory update too.
 *
 * On failure, writes a machine-readable markdown report to
 * `reports/security-memory-drift.md` so a downstream workflow can post it as
 * a PR comment with the exact keys that drifted.
 */
import { execSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const MEMORY = "docs/security/security-memory.md";
const ACCEPTED = "docs/security/findings.accepted.json";
const RLS_FIXTURE = "tests/security/__fixtures__/rls.expected.json";
const MIGRATIONS_PREFIX = "supabase/migrations/";
const REPORT_PATH = resolve(process.cwd(), "reports/security-memory-drift.md");

function safe(cmd: string): string {
  try {
    return execSync(cmd, { encoding: "utf8" });
  } catch {
    return "";
  }
}

function diffBase(): string {
  const baseRef = process.env.GITHUB_BASE_REF;
  if (baseRef) {
    try {
      execSync(`git fetch --no-tags --depth=50 origin ${baseRef}`, { stdio: "ignore" });
      return `origin/${baseRef}`;
    } catch {
      // fall through
    }
  }
  try {
    execSync("git rev-parse HEAD~1", { stdio: "ignore" });
    return "HEAD~1";
  } catch {
    return "";
  }
}

const base = diffBase();
if (!base) {
  console.log("[security-memory-drift] no git base to diff against; skipping");
  process.exit(0);
}

const raw = safe(`git diff --name-only ${base}...HEAD`);
const changed = new Set(raw.split("\n").filter(Boolean));

const memoryChanged = changed.has(MEMORY);
const acceptedChanged = changed.has(ACCEPTED);
const fixtureChanged = changed.has(RLS_FIXTURE);
const migrationAdded = [...changed].some((f) => f.startsWith(MIGRATIONS_PREFIX));

interface Drift {
  file: string;
  reason: string;
  changedKeys: string[];
}
const drifts: Drift[] = [];

/** Extract heading keys that changed in a file (best-effort, textual). */
function changedHeadings(file: string): string[] {
  const diff = safe(`git diff ${base}...HEAD -- ${file}`);
  const keys = new Set<string>();
  for (const line of diff.split("\n")) {
    // Added or removed markdown headings / bolded keys
    const md = line.match(/^[+-](#+ .+|\*\*[^*]+\*\*)$/);
    if (md) keys.add(md[1].replace(/^\*+|\*+$/g, "").trim());
    // JSON-ish lines that touch internal_id
    const idMatch = line.match(/^[+-].*"internal_id"\s*:\s*"([^"]+)"/);
    if (idMatch) keys.add(`internal_id:${idMatch[1]}`);
  }
  return Array.from(keys).slice(0, 20);
}

if (memoryChanged && !(acceptedChanged || fixtureChanged || migrationAdded)) {
  drifts.push({
    file: MEMORY,
    reason: `changed without a paired update to ${ACCEPTED}, ${RLS_FIXTURE}, or a new ${MIGRATIONS_PREFIX}* file`,
    changedKeys: changedHeadings(MEMORY),
  });
}
if (acceptedChanged && !memoryChanged) {
  drifts.push({
    file: ACCEPTED,
    reason: `changed without a paired update to ${MEMORY}`,
    changedKeys: changedHeadings(ACCEPTED),
  });
}

mkdirSync(resolve(process.cwd(), "reports"), { recursive: true });

if (drifts.length === 0) {
  writeFileSync(REPORT_PATH, `# Security memory drift check\n\n:white_check_mark: OK — no drift detected.\n`);
  console.log("[security-memory-drift] ok");
  process.exit(0);
}

const md = [
  `# :warning: Security memory drift detected`,
  ``,
  `The paired-update rule was violated. Update security memory and the corresponding invariants/findings file together.`,
  ``,
  ...drifts.flatMap((d) => [
    `## \`${d.file}\``,
    ``,
    `**Why**: ${d.reason}`,
    ``,
    d.changedKeys.length
      ? `**Changed keys**:\n\n${d.changedKeys.map((k) => `- \`${k}\``).join("\n")}`
      : `_(No specific keys extracted from the diff.)_`,
    ``,
  ]),
  `_Auto-generated by \`scripts/check-security-memory-drift.ts\`._`,
].join("\n");

writeFileSync(REPORT_PATH, md);
console.error("[security-memory-drift] paired-update rule violated");
for (const d of drifts) console.error(` - ${d.file}: ${d.reason}`);
process.exit(1);
