/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ReadinessRouteImport } from './routes/readiness'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpportunitiesMapRouteImport } from './routes/opportunities.map'
import { Route as CredentialIdRouteImport } from './routes/credential.$id'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessRoute = ReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesMapRoute = OpportunitiesMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => OpportunitiesRoute,
} as any)
const CredentialIdRoute = CredentialIdRouteImport.update({
  id: '/credential/$id',
  path: '/credential/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/readiness': typeof ReadinessRoute
  '/security': typeof SecurityRoute
  '/skills': typeof SkillsRoute
  '/credential/$id': typeof CredentialIdRoute
  '/opportunities/map': typeof OpportunitiesMapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/readiness': typeof ReadinessRoute
  '/security': typeof SecurityRoute
  '/skills': typeof SkillsRoute
  '/credential/$id': typeof CredentialIdRoute
  '/opportunities/map': typeof OpportunitiesMapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/readiness': typeof ReadinessRoute
  '/security': typeof SecurityRoute
  '/skills': typeof SkillsRoute
  '/credential/$id': typeof CredentialIdRoute
  '/opportunities/map': typeof OpportunitiesMapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/opportunities'
    | '/readiness'
    | '/security'
    | '/skills'
    | '/credential/$id'
    | '/opportunities/map'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/opportunities'
    | '/readiness'
    | '/security'
    | '/skills'
    | '/credential/$id'
    | '/opportunities/map'
  id:
    | '__root__'
    | '/'
    | '/opportunities'
    | '/readiness'
    | '/security'
    | '/skills'
    | '/credential/$id'
    | '/opportunities/map'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpportunitiesRoute: typeof OpportunitiesRouteWithChildren
  ReadinessRoute: typeof ReadinessRoute
  SecurityRoute: typeof SecurityRoute
  SkillsRoute: typeof SkillsRoute
  CredentialIdRoute: typeof CredentialIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness': {
      id: '/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/map': {
      id: '/opportunities/map'
      path: '/map'
      fullPath: '/opportunities/map'
      preLoaderRoute: typeof OpportunitiesMapRouteImport
      parentRoute: typeof OpportunitiesRoute
    }
    '/credential/$id': {
      id: '/credential/$id'
      path: '/credential/$id'
      fullPath: '/credential/$id'
      preLoaderRoute: typeof CredentialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OpportunitiesRouteChildren {
  OpportunitiesMapRoute: typeof OpportunitiesMapRoute
}

const OpportunitiesRouteChildren: OpportunitiesRouteChildren = {
  OpportunitiesMapRoute: OpportunitiesMapRoute,
}

const OpportunitiesRouteWithChildren = OpportunitiesRoute._addFileChildren(
  OpportunitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpportunitiesRoute: OpportunitiesRouteWithChildren,
  ReadinessRoute: ReadinessRoute,
  SecurityRoute: SecurityRoute,
  SkillsRoute: SkillsRoute,
  CredentialIdRoute: CredentialIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
