/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustGraphRouteImport } from './routes/trust-graph'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ReadinessRouteImport } from './routes/readiness'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SecurityFindingsHistoryRouteImport } from './routes/security.findings-history'
import { Route as OpportunitiesMapRouteImport } from './routes/opportunities.map'
import { Route as CredentialIdRouteImport } from './routes/credential.$id'
import { Route as ApiSecurityHistoryFileRouteImport } from './routes/api/security/history.$file'

const TrustGraphRoute = TrustGraphRouteImport.update({
  id: '/trust-graph',
  path: '/trust-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessRoute = ReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityFindingsHistoryRoute = SecurityFindingsHistoryRouteImport.update({
  id: '/findings-history',
  path: '/findings-history',
  getParentRoute: () => SecurityRoute,
} as any)
const OpportunitiesMapRoute = OpportunitiesMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => OpportunitiesRoute,
} as any)
const CredentialIdRoute = CredentialIdRouteImport.update({
  id: '/credential/$id',
  path: '/credential/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSecurityHistoryFileRoute = ApiSecurityHistoryFileRouteImport.update({
  id: '/api/security/history/$file',
  path: '/api/security/history/$file',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/readiness': typeof ReadinessRoute
  '/security': typeof SecurityRouteWithChildren
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/trust-graph': typeof TrustGraphRoute
  '/credential/$id': typeof CredentialIdRoute
  '/opportunities/map': typeof OpportunitiesMapRoute
  '/security/findings-history': typeof SecurityFindingsHistoryRoute
  '/api/security/history/$file': typeof ApiSecurityHistoryFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/readiness': typeof ReadinessRoute
  '/security': typeof SecurityRouteWithChildren
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/trust-graph': typeof TrustGraphRoute
  '/credential/$id': typeof CredentialIdRoute
  '/opportunities/map': typeof OpportunitiesMapRoute
  '/security/findings-history': typeof SecurityFindingsHistoryRoute
  '/api/security/history/$file': typeof ApiSecurityHistoryFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/readiness': typeof ReadinessRoute
  '/security': typeof SecurityRouteWithChildren
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/trust-graph': typeof TrustGraphRoute
  '/credential/$id': typeof CredentialIdRoute
  '/opportunities/map': typeof OpportunitiesMapRoute
  '/security/findings-history': typeof SecurityFindingsHistoryRoute
  '/api/security/history/$file': typeof ApiSecurityHistoryFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/opportunities'
    | '/readiness'
    | '/security'
    | '/settings'
    | '/skills'
    | '/trust-graph'
    | '/credential/$id'
    | '/opportunities/map'
    | '/security/findings-history'
    | '/api/security/history/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/opportunities'
    | '/readiness'
    | '/security'
    | '/settings'
    | '/skills'
    | '/trust-graph'
    | '/credential/$id'
    | '/opportunities/map'
    | '/security/findings-history'
    | '/api/security/history/$file'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/opportunities'
    | '/readiness'
    | '/security'
    | '/settings'
    | '/skills'
    | '/trust-graph'
    | '/credential/$id'
    | '/opportunities/map'
    | '/security/findings-history'
    | '/api/security/history/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  OpportunitiesRoute: typeof OpportunitiesRouteWithChildren
  ReadinessRoute: typeof ReadinessRoute
  SecurityRoute: typeof SecurityRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  TrustGraphRoute: typeof TrustGraphRoute
  CredentialIdRoute: typeof CredentialIdRoute
  ApiSecurityHistoryFileRoute: typeof ApiSecurityHistoryFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust-graph': {
      id: '/trust-graph'
      path: '/trust-graph'
      fullPath: '/trust-graph'
      preLoaderRoute: typeof TrustGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness': {
      id: '/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/findings-history': {
      id: '/security/findings-history'
      path: '/findings-history'
      fullPath: '/security/findings-history'
      preLoaderRoute: typeof SecurityFindingsHistoryRouteImport
      parentRoute: typeof SecurityRoute
    }
    '/opportunities/map': {
      id: '/opportunities/map'
      path: '/map'
      fullPath: '/opportunities/map'
      preLoaderRoute: typeof OpportunitiesMapRouteImport
      parentRoute: typeof OpportunitiesRoute
    }
    '/credential/$id': {
      id: '/credential/$id'
      path: '/credential/$id'
      fullPath: '/credential/$id'
      preLoaderRoute: typeof CredentialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/security/history/$file': {
      id: '/api/security/history/$file'
      path: '/api/security/history/$file'
      fullPath: '/api/security/history/$file'
      preLoaderRoute: typeof ApiSecurityHistoryFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OpportunitiesRouteChildren {
  OpportunitiesMapRoute: typeof OpportunitiesMapRoute
}

const OpportunitiesRouteChildren: OpportunitiesRouteChildren = {
  OpportunitiesMapRoute: OpportunitiesMapRoute,
}

const OpportunitiesRouteWithChildren = OpportunitiesRoute._addFileChildren(
  OpportunitiesRouteChildren,
)

interface SecurityRouteChildren {
  SecurityFindingsHistoryRoute: typeof SecurityFindingsHistoryRoute
}

const SecurityRouteChildren: SecurityRouteChildren = {
  SecurityFindingsHistoryRoute: SecurityFindingsHistoryRoute,
}

const SecurityRouteWithChildren = SecurityRoute._addFileChildren(
  SecurityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  OpportunitiesRoute: OpportunitiesRouteWithChildren,
  ReadinessRoute: ReadinessRoute,
  SecurityRoute: SecurityRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  TrustGraphRoute: TrustGraphRoute,
  CredentialIdRoute: CredentialIdRoute,
  ApiSecurityHistoryFileRoute: ApiSecurityHistoryFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
