// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Generic auth-failure responses. We deliberately do NOT distinguish between
// "no header", "malformed header", and "invalid token" externally — that
// telemetry leaks information to credential-stuffing attackers. Server logs
// retain the granular reason for operators.
function unauthorized(): Response {
  return new Response("Unauthorized", {
    status: 401,
    headers: { "WWW-Authenticate": 'Bearer realm="api"' },
  });
}

function isLikelyJwt(token: string): boolean {
  // 3 base64url segments separated by "." — cheap pre-flight to avoid a
  // network round-trip for obviously malformed tokens.
  if (token.length < 20 || token.length > 8192) return false;
  const parts = token.split(".");
  if (parts.length !== 3) return false;
  return parts.every((p) => /^[A-Za-z0-9_-]+$/.test(p));
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      // Don't echo env-var names back to the caller.
      console.error("auth-middleware: Supabase env vars are not configured");
      throw new Response("Service misconfigured", { status: 500 });
    }

    const request = getRequest();
    if (!request?.headers) throw unauthorized();

    const authHeader = request.headers.get("authorization");
    if (!authHeader || !/^Bearer\s+/i.test(authHeader)) throw unauthorized();

    const token = authHeader.replace(/^Bearer\s+/i, "").trim();
    if (!token || !isLikelyJwt(token)) throw unauthorized();

    const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims?.sub) throw unauthorized();

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
