// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

/**
 * Minimal Web Storage adapter that prefers `sessionStorage` (cleared on tab
 * close) and falls back to `localStorage` if the user explicitly opted into
 * "remember me" by setting `talentgraph:auth:remember = "1"` somewhere.
 *
 * Defence in depth — a stored access token in sessionStorage is still
 * exposed to any same-origin script that runs in the page. Strong CSP +
 * never echoing user-supplied HTML are the primary mitigations.
 */
function safeStorage(): Storage | undefined {
  if (typeof window === "undefined") return undefined;
  try {
    const remember = window.localStorage.getItem("talentgraph:auth:remember") === "1";
    return remember ? window.localStorage : window.sessionStorage;
  } catch {
    return undefined;
  }
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error(
      "Missing Supabase environment variables. Ensure SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY (or VITE_ prefixed versions) are set in your .env file.",
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: safeStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
